const { withInfoPlist, withAppDelegate, withXcodeProject, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const SCENE_DELEGATE_SOURCE = `// Generated by withIosSceneDelegate config plugin — do not edit by hand.
internal import Expo

class SceneDelegate: ExpoAppSceneDelegate {}
`;

// iOS 27 requires apps to adopt the UIScene life cycle or they fail to launch.
// Expo 57.0.23 added an opt-in ExpoAppSceneDelegate base class (expo/expo#50191),
// but wiring it up (Info.plist, AppDelegate, and the new source file) is left to the app.
// This plugin does that wiring so it survives every `expo prebuild`, since ios/ isn't committed.
function withIosSceneDelegate(config) {
  config = withInfoPlist(config, (config) => {
    config.modResults.UIApplicationSceneManifest = {
      UIApplicationSupportsMultipleScenes: false,
      UISceneConfigurations: {
        UIWindowSceneSessionRoleApplication: [
          {
            UISceneConfigurationName: 'Default Configuration',
            UISceneDelegateClassName: '$(PRODUCT_MODULE_NAME).SceneDelegate',
          },
        ],
      },
    };
    return config;
  });

  config = withAppDelegate(config, (config) => {
    if (config.modResults.language !== 'swift') {
      throw new Error('withIosSceneDelegate only supports Swift AppDelegates');
    }
    let contents = config.modResults.contents;

    if (!contents.includes('ExpoReactNativeFactoryProvider')) {
      contents = contents.replace(
        'class AppDelegate: ExpoAppDelegate {',
        'class AppDelegate: ExpoAppDelegate, ExpoReactNativeFactoryProvider {'
      );
    }

    // The scene delegate now creates the window and starts React Native from
    // `scene(_:willConnectTo:options:)`; doing it again here would start RN twice.
    contents = contents.replace(
      /\s*#if os\(iOS\) \|\| os\(tvOS\)\n\s*window = UIWindow\(frame: UIScreen\.main\.bounds\)\n\s*factory\.startReactNative\(\n\s*withModuleName: "main",\n\s*in: window,\n\s*launchOptions: launchOptions\)\n\s*#endif\n/,
      '\n'
    );

    config.modResults.contents = contents;
    return config;
  });

  config = withDangerousMod(config, [
    'ios',
    async (config) => {
      const sceneDelegatePath = path.join(
        config.modRequest.platformProjectRoot,
        config.modRequest.projectName,
        'SceneDelegate.swift'
      );
      fs.writeFileSync(sceneDelegatePath, SCENE_DELEGATE_SOURCE);
      return config;
    },
  ]);

  config = withXcodeProject(config, (config) => {
    const project = config.modResults;
    const relativePath = `${config.modRequest.projectName}/SceneDelegate.swift`;

    if (project.hasFile(relativePath)) {
      return config;
    }

    const groups = project.hash.project.objects.PBXGroup;
    const mainGroupKey = Object.keys(groups).find((key) => {
      const group = groups[key];
      return Array.isArray(group.children) && group.children.some((c) => c.comment === 'AppDelegate.swift');
    });

    if (!mainGroupKey) {
      throw new Error('withIosSceneDelegate could not find the group containing AppDelegate.swift');
    }

    project.addSourceFile(relativePath, null, mainGroupKey);
    return config;
  });

  return config;
}

module.exports = withIosSceneDelegate;
